# Stage 1: Build the extensions
FROM rust:1.91.1 AS builder

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    wget ca-certificates gnupg \
    nodejs npm \
    libpq-dev \
    postgresql-server-dev-all \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

# Get pgrx
RUN cargo install --locked cargo-pgrx
RUN cargo pgrx init --pg17 /usr/bin/pg_config

# Build the extensions
WORKDIR /build

COPY Cargo.toml clippy.toml rust-toolchain.toml rustfmt.toml  ./
COPY crates crates
COPY packages packages

RUN pnpm --dir ./packages/runtime install

# Build & install the extensions
# RUN cargo build --release -p plts -p stopgap
RUN cargo pgrx install --release -p plts \
    && cargo pgrx install --release -p stopgap

# Stage 2: Create the final image
FROM postgres:17

# Copy compiled extension binaries from builder
COPY --from=builder /build/target/release/plts--*.so /usr/lib/postgresql/17/lib/
COPY --from=builder /build/target/release/stopgap--*.so /usr/lib/postgresql/17/lib/

# Copy extension control files
COPY --from=builder /build/target/release/plts.control /usr/share/postgresql/17/extension/
COPY --from=builder /build/target/release/stopgap.control /usr/share/postgresql/17/extension/

# Initialize with extensions
USER postgres
RUN echo "CREATE EXTENSION IF NOT EXISTS plts;" >> /docker-entrypoint-initdb.d/01-plts.sql
RUN echo "CREATE EXTENSION IF NOT EXISTS stopgap;" >> /docker-entrypoint-initdb.d/02-stopgap.sql
